### PR TITLE
Issue 374

### PR DESCRIPTION
**Pull request by atombender**
Big change to mangling format. Increases index format version. #374

### CODE REVIEW

**Comment by erikgrinaker** [comment]
Ran a full resync of production data, got this error:

```
13:23:27.510 INFO system Full resync of namespace "4opb80h7.production.HNQlM4ISFxVV" needed
panic: cannot mangle attribute ("overview") of type datatypes.nilType{}

goroutine 5072 [running]:
github.com/sanity-io/gradient/pkg/search/elasticsearch/indexformat.NewField(0xc423bc4670, 0x8, 0x2042e80, 0x221f858, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/erik/Projects/go/src/github.com/sanity-io/gradient/pkg/search/elasticsearch/indexformat/fields.go:23 +0x253
github.com/sanity-io/gradient/pkg/search/elasticsearch/indexformat.Field.Child(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1, ...)
	/Users/erik/Projects/go/src/github.com/sanity-io/gradient/pkg/search/elasticsearch/indexformat/fields.go:131 +0xcc
github.com/sanity-io/gradient/pkg/search/elasticsearch/indexformat.Field.WithArray(...)
	/Users/erik/Projects/go/src/github.com/sanity-io/gradient/pkg/search/elasticsearch/indexformat/mangler.go:258
github.com/sanity-io/gradient/pkg/search/elasticsearch/indexformat.(*mangler).doMapKVArray(0xc42037e140, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/erik/Projects/go/src/github.com/sanity-io/gradient/pkg/search/elasticsearch/indexformat/mangler.go:258 +0x498
github.com/sanity-io/gradient/pkg/search/elasticsearch/indexformat.(*mangler).doMapKV(0xc42037e140, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/erik/Projects/go/src/github.com/sanity-io/gradient/pkg/search/elasticsearch/indexformat/mangler.go:155 +0x1c8
github.com/sanity-io/gradient/pkg/search/elasticsearch/indexformat.(*mangler).doMap.func1(0xc423bc4670, 0x8, 0x1924ea0, 0xc4213ce4a0, 0xc4213ce4a0, 0x98)
	/Users/erik/Projects/go/src/github.com/sanity-io/gradient/pkg/search/elasticsearch/indexformat/mangler.go:121 +0x1fe
github.com/sanity-io/gradient/pkg/search/elasticsearch/indexformat.iterateStringMap(0x1a12ea0, 0xc42570ac00, 0xc424b0b978, 0x30, 0x1a679c0)
	/Users/erik/Projects/go/src/github.com/sanity-io/gradient/pkg/search/elasticsearch/indexformat/utils.go:14 +0x1bb
github.com/sanity-io/gradient/pkg/search/elasticsearch/indexformat.(*mangler).doMap(0xc42037e140, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/erik/Projects/go/src/github.com/sanity-io/gradient/pkg/search/elasticsearch/indexformat/mangler.go:110 +0xcc
github.com/sanity-io/gradient/pkg/search/elasticsearch/indexformat.(*mangler).Mangle(0xc42037e140, 0xc425264100, 0x20, 0xc42570ac00, 0x1987e20, 0xc4201c15c0, 0x0)
	/Users/erik/Projects/go/src/github.com/sanity-io/gradient/pkg/search/elasticsearch/indexformat/mangler.go:98 +0x2d8
github.com/sanity-io/gradient/pkg/search/elasticsearch/indexing.(*receiver).itemFromDocument(0xc4205820c0, 0xc424aa1c00, 0xc423bb2b00, 0x20, 0x117ee01)
	/Users/erik/Projects/go/src/github.com/sanity-io/gradient/pkg/search/elasticsearch/indexing/receiver.go:170 +0x6a
github.com/sanity-io/gradient/pkg/search/elasticsearch/indexing.(*resync).StoreDocument(0xc4220bebe0, 0xc424aa1c00, 0x10, 0xc438d7fee0)
	/Users/erik/Projects/go/src/github.com/sanity-io/gradient/pkg/search/elasticsearch/indexing/receiver.go:239 +0x15d
github.com/sanity-io/gradient/pkg/documents/syncing/full.(*Syncer).doSync(0xc4220becd0, 0x0, 0x0)
	/Users/erik/Projects/go/src/github.com/sanity-io/gradient/pkg/documents/syncing/full/full.go:157 +0x3ba
github.com/sanity-io/gradient/pkg/documents/syncing/full.(*Syncer).run(0xc4220becd0)
	/Users/erik/Projects/go/src/github.com/sanity-io/gradient/pkg/documents/syncing/full/full.go:72 +0x2f
created by github.com/sanity-io/gradient/pkg/documents/syncing/full.New
	/Users/erik/Projects/go/src/github.com/sanity-io/gradient/pkg/documents/syncing/full/full.go:51 +0x1e0
```

**Comment by atombender** [comment]
@erikgrinaker Pushed fix.

**Comment by erikgrinaker** [comment]
Thanks. I've run a full sync, which has completed without error except for a single pending namespace with millions of documents - I'll let you know if it fails.

**Comment by atombender** [comment]
Resolved conflicts against master. Because this wasn't merged earlier, it got out of sync, and the conflict was gnarly around the logic for `in` pushdown. I hope I resolved it correctly. :|

**Comment by erikgrinaker** [comment]
Already merged into `dev`.

**Pull request closed without merging**
