### PR TITLE
Allow querying on reference fields using strings (closes #493)

### LINKED ISSUE #493: Handle ref comparison with strings
This apparently fails:

```
*[famousFor._ref == "aliens"]._id
```

### PR DESCRIPTION
**Pull request by erikgrinaker**
Fixes #493 by indexing a copy of the original reference object, to allow for subsequent querying of e.g. `movie._ref == "aliens"` or `movie._weak == false`.

Existing documents must unfortunately be reindexed for this to work.

### CODE REVIEW

**Comment by atombender** [comment]
This will also require an update to [the mappings](https://github.com/sanity-io/gradient/blob/master/pkg/search/elasticsearch/indexformat/indexformat.go#L187). 

You'll also need to remove the ref type from `TypeSuffixes` and from `SupportedTypes`.

**Comment by atombender** [comment]
By updating the mapping I mean removing it and `TypeSuffixReference`.

**Comment by erikgrinaker** [comment]
I don't believe that's necessary. The old `*$r` reference field is still used, but we set an extra `*$m` field for the reference as well, to allow for richer querying. This is analogous to how datetime fields are indexed in multiple formats.

**Comment by atombender** [comment]
I see, you just added an additional key. I'm not sure I see the point of having both, but I guess we can phase out `$r` later if we need to.

**Comment by erikgrinaker** [comment]
@simen Do you have an opinion on keeping or removing the `$r` keys? I suppose removing them would be a breaking API change, thus a no-go?

**Comment by erikgrinaker** [comment]
Simen agreed that we should remove `$r` while we're at it, since it's never worked anyway.

Removing the Ref type from the mangler as @atombender outlined would require removing the Ref datatype entirely, but I consider it to be a conceptually distinct type and thus useful to keep around. So I've instead just set the mangler to explicitly treat refs as maps.

I'd appreciate a final 👍 before merging this, @atombender.

**Comment by atombender** [comment]
Looks good. 👍  We shouldn't remove `Ref` as a datatype yet, because the type system still allows for validation. However, something we probably to do soon is move "structural types" (refs, GeoJSON, typed nested documents) into the schema subsystem, and let the datatype system only concern itself with purely primitive types.

**Pull request merged**
